const POST_PRODUCT = "POST_PRODUCT"
const UPDATE_PRODUCT = "UPDATE_PRODUCT"
const INIT = "INIT"
const POST_MENSAJE = "POST_MENSAJE"
const NEW_MENSAJE = "NEW_MENSAJE"

module.exports = {
    POST_PRODUCT,
    UPDATE_PRODUCT,
    INIT,
    POST_MENSAJE,
    NEW_MENSAJE
}